# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e49c77d441ed854603deb7291fc8685bfbb58fc42d4b7afe34c5eff66edf848287fe078d1e43da710f757dccfe75147ed6debd3a77e426790a62e38eada3156a

test:
  secret_key_base: 5a3dd2c0341a1a10f533d5601a82d2d36a721eef272077dd35756e030b2ab72f4d6e82113d17cee85d0f2bf2ab1aa3a25ecb8ee8b9fb6988cf7969625d6502b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
