source 'https://rubygems.org'

gem 'bcrypt'

gem 'rails'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jbuilder'

group :development, :test do
  gem 'pry-rails'
end

